trigger:
  - feature/azure-pipeline
  - develop

pr:
  - develop

stages:
  - stage:
    jobs:
      - job: tnotif
        displayName: "Deploy Tnotif"
        pool:
          vmImage: "ubuntu-18.04"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: baitregistry
          - task: Docker@2
            displayName: "Build and Push"
            inputs:
              command: buildAndPush
              containerRegistry: baitregistry
              repository: tnotif
              tag: ${Build.BuildId}
          - task: HelmInstaller@1
            displayName: "Install Helm"
            inputs:
              helmVersionToInstall: 3.3.0
          - task: HelmDeploy@0
            displayName: Helm Upgrade
            inputs:
              kubernetesServiceEndpoint: baitkubernetescluster
              connectionType: "Kubernetes Service Connection"
              azureResourceGroup: ba-it-tools
              kubernetesCluster: ba-it-aks-cluster
              command: upgrade
              chartType: filepath
              chartPath: tnotifchart
              releaseName: tnotif
              install: true
              overrideValues: "image.tag=$(Build.BuildId)"
              waitForExecution: false
        condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/')
