version: '3'
services:
    app:
        image: golang
        command: ["go", "run", "main.go"]
        working_dir: /Users/yuly.gunawan/workspace/tnotif
        volumes:
            - .:/Users/yuly.gunawan/workspace/tnotif
        ports: 
            - 8082:8082
        depends_on:
            - postgres
        links: 
            - postgres

    postgres:
        image: postgres:12.3-alpine
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db

volumes: 
    main_data: {}
    db_data: {}
