version: "3"
services:
    tnotif:
        build: .
        command: ["go", "run", "main.go"]
        working_dir: /workspace/tnotif
        volumes:
            - .:/workspace/tnotif
        ports:
            - 8082:8082
        depends_on:
            - postgres
            # - filebeat

    postgres:
        image: postgres:12.3-alpine
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5435:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db



volumes:
    main_data: {}
    db_data: {}
